apiVersion: apps/v1
kind: Deployment
metadata:
  name: myrabbitconsumer
spec:
  selector:
    matchLabels:
      app: myrabbitconsumer
  template:
    metadata:
      labels:
        app: myrabbitconsumer
    spec:
      containers:
      - name: myrabbitconsumer
        image: alvinsoo1993/myrabbitconsumer
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
