apiVersion: apps/v1
kind: Deployment
metadata:
  name: myrabbitconsumer
spec:
  selector:
    matchLabels:
      app: myrabbitconsumer
  template:
    metadata:
      labels:
        app: myrabbitconsumer
    spec:
      containers:
      - name: myrabbitconsumer
        image: alvinsoo1993/myrabbitconsumer:latest
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
---
apiVersion: v1
kind: Service
metadata:
  name: myrabbitconsumer
spec:
  type: NodePort
  selector:
    app: myrabbitconsumer
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 32500